-- BullInsights Database Schema

-- 1. Stocks Table
CREATE TABLE IF NOT EXISTS stocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    exchange VARCHAR(50) DEFAULT 'NASDAQ',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. News Articles Table
CREATE TABLE IF NOT EXISTS news_articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_id BIGINT REFERENCES stocks(id) ON DELETE CASCADE,
    symbol VARCHAR(20) NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    text TEXT,
    source VARCHAR(255),
    url TEXT NOT NULL UNIQUE,
    published_at TIMESTAMP WITH TIME ZONE,
    source_api VARCHAR(100),
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. Stock Prices Table (historical OHLCV)
CREATE TABLE IF NOT EXISTS stock_prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_id BIGINT REFERENCES stocks(id) ON DELETE CASCADE,
    symbol VARCHAR(20) NOT NULL,
    date DATE NOT NULL,
    open NUMERIC(14, 4) NOT NULL CHECK (open >= 0),
    high NUMERIC(14, 4) NOT NULL CHECK (high >= 0),
    low NUMERIC(14, 4) NOT NULL CHECK (low >= 0),
    close NUMERIC(14, 4) NOT NULL CHECK (close >= 0),
    volume BIGINT NOT NULL CHECK (volume >= 0),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_stock_date UNIQUE (stock_id, date)
);

-- 4. Live Stock Prices Table
-- Kept separate from stock_prices so the dashboard can read the latest
-- Twelve Data quote without scanning historical OHLCV records.
CREATE TABLE IF NOT EXISTS stock_latest (
    symbol TEXT PRIMARY KEY,
    price DOUBLE PRECISION NOT NULL,
    change DOUBLE PRECISION,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Sentiment Scores Table (FinBERT Output)
CREATE TABLE IF NOT EXISTS sentiment_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id BIGINT REFERENCES news_articles(id) ON DELETE CASCADE,
    symbol VARCHAR(20) NOT NULL,
    positive_prob NUMERIC(6, 5) CHECK (positive_prob BETWEEN 0 AND 1),
    negative_prob NUMERIC(6, 5) CHECK (negative_prob BETWEEN 0 AND 1),
    neutral_prob NUMERIC(6, 5) CHECK (neutral_prob BETWEEN 0 AND 1),
    composite_score NUMERIC(6, 5) CHECK (composite_score BETWEEN -1 AND 1),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 6. Predictions Table (ML Outputs)
CREATE TABLE IF NOT EXISTS predictions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_id BIGINT REFERENCES stocks(id) ON DELETE CASCADE,
    symbol VARCHAR(20) NOT NULL,
    prediction_date DATE NOT NULL,
    target_date DATE NOT NULL,
    predicted_return NUMERIC(10, 6) NOT NULL,
    predicted_price NUMERIC(14, 4) NOT NULL,
    model_name VARCHAR(100) NOT NULL,
    metrics JSONB,
    horizon VARCHAR(20) NOT NULL DEFAULT '1d',
    horizon_sessions INTEGER,
    forecast_type VARCHAR(30),
    lower_return NUMERIC(10, 6),
    upper_return NUMERIC(10, 6),
    lower_price NUMERIC(14, 4),
    upper_price NUMERIC(14, 4),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_stock_pred_target_horizon UNIQUE (stock_id, prediction_date, target_date, model_name, horizon)
);

-- Indexes for Query Optimization
CREATE INDEX IF NOT EXISTS idx_news_articles_published_at ON news_articles(published_at DESC);
CREATE INDEX IF NOT EXISTS idx_news_articles_symbol ON news_articles(symbol);
CREATE INDEX IF NOT EXISTS idx_stock_prices_symbol_date ON stock_prices(symbol, date DESC);
CREATE INDEX IF NOT EXISTS idx_predictions_symbol_target ON predictions(symbol, target_date DESC);\nCREATE INDEX IF NOT EXISTS idx_predictions_model_horizon_target ON predictions(model_name, horizon, target_date DESC);
CREATE INDEX IF NOT EXISTS idx_stock_latest_timestamp ON stock_latest(timestamp DESC);
